name: defyx_vpn
description: "A new Vpn app"
publish_to: "none"
version: 3.8.2+234

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  # Backend Packages
  flutter_riverpod: ^3.1.0
  go_router: ^17.0.1
  shared_preferences: ^2.2.2
  dio: ^5.7.0
  dio_http_formatter: ^3.2.1
  shimmer: ^3.0.0
  shake: ^3.0.0
  vibration: ^3.1.3
  google_mobile_ads: ^7.0.0
  url_launcher: ^6.3.1
  flame: ^1.29.0
  webview_flutter: ^4.13.0
  async: ^2.12.0
  flutter_secure_storage: ^10.0.0
  freezed_annotation: ^3.1.0
  retrofit: ^4.9.1
  json_annotation: ^4.9.0
  package_info_plus: ^9.0.0
  version: ^3.0.2
  flutter_timezone: ^5.0.1
  connectivity_plus: ^7.0.0

  # Frontend Packages
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.1.0
  lottie: ^3.3.1
  toastification: ^3.0.3
  path_drawing: ^1.0.1
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^6.0.0
  firebase_core: ^4.2.0
  firebase_analytics: ^12.0.3
  battery_plus: ^7.0.0
  audioplayers: ^6.5.1
  path_provider: ^2.1.1
  msix: ^3.16.12
  flutter_native_splash: ^2.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.7.1
  retrofit_generator: ^10.2.0
  json_serializable: ^6.8.0
  freezed: ^3.2.3
  riverpod_generator: ^4.0.0+1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/lottie/
    - assets/flags/
    - assets/sounds/
    - .env

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/Lato-Thin.ttf
          weight: 100
        - asset: assets/fonts/Lato-Black.ttf
          weight: 900

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash-light-logo.png
  color_dark: "#000000"
  image_dark: assets/images/splash-dark-logo.png

  android: true
  ios: true
  web: false

msix_config:
  display_name: Defyx VPN
  publisher_display_name: UnboundTech UG
  identity_name: UnboundTechUG.6065AEC5A207
  msix_version: 3.8.2.0
  publisher: "CN=62937938-2AE2-4C12-9ED8-4C418C0CADF2"
  logo_path: assets/images/logo.png
  capabilities: runFullTrust,internetClientServer,privateNetworkClientServer,unvirtualizedResources
  execution_alias: defyxvpn
  architecture: x64
  languages: en-us
  install_certificate: false
  enable_at_startup: false

